//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enrollment
    {
        public int EnrollmentID { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public int CourseID { get; set; }
        public int StudentID { get; set; }
        public int PaymentTypeID { get; set; }
        public int TrainingID { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual PaymentType PaymentType { get; set; }
        public virtual Student Student { get; set; }
        public virtual Training Training { get; set; }
    }
}
